##
# Makefile automatically generated by genmake 1.0, May-03-00
# genmake 1.0 by muquit@muquit.com, http://www.muquit.com/

TAVERN_PKG=pkg/tavern
HERO_PKG=pkg/hero
LAND_PKG=pkg/land
PROFILE_PKG=pkg/profile

NATIVE_DIR=./bin
LINUX_DIR=./bin/linux
WINDOWS_DIR=./bin/windows
PI_DIR=./bin/pi
PI_JESSIE_DIR=./bin/pi_jessie
MAC_DIR=./bin/mac

all: native mac linux windows pi pi_jessie

native:
	@echo "- Compiling native binaries ... Binaries will be created in ./bin directory"
	go build -o ./bin ./...
	@echo ""

mac:
	@echo "- Compiling for MacOS ... Binaries will be in ./bin/mac directory"
	CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./bin/mac ./...
	@echo ""

linux:
	@echo "- Compiling for linux ... Binaries will be in ./bin/linux directory"
	CGO_ENABLED=0 GOOS=linux go build -o ./bin/linux ./...
	@echo ""

windows:
	@echo "- Compiling for Windows 64bit ... Binaries will be in ./bin/windows directory"
	CGO_ENABLED=0 GOOS=windows GOARGC=386 go build -o ./bin/windows ./...
	@echo ""

pi:
	@echo "- Compiling for Raspberry PI ... Binaries will be in ./bin/pi directory"
	GOOS=linux GOARCH=arm GOARM=7 go build -o ./bin/pi ./...
	@echo ""

pi_jessie:
	@echo "- Compiling for Raspberry jessie ... Binaries will be in ./bin/pi_jessie directory"
	GOARM=6 GOARCH=arm GOOS=linux go build -o ./bin/pi_jessie ./...
	@echo ""


abi:
	@mkdir -p $(TAVERN_PKG)
	@mkdir -p $(HERO_PKG)
	@mkdir -p $(LAND_PKG)
	@mkdir -p $(PROFILE_PKG)
	abigen --abi abis/hero.json --pkg hero --type Hero --out $(HERO_PKG)/hero.go
	abigen --abi abis/tavern.json --pkg tavern --type Tavern --out $(TAVERN_PKG)/tavern.go
	abigen --abi abis/land.json --pkg land --type Land --out $(LAND_PKG)/land.go
	abigen --abi abis/profile.json --pkg profile --type Profile --out $(PROFILE_PKG)/profile.go

tidy:
	go mod tidy

clean_native:
	@/bin/rm -f ./bin/* 

clean:
	/bin/rm -f $(LINUX_DIR)/* >/dev/null 2>&1
	/bin/rm -f $(WINDOWS_DIR)/* >/dev/null 2>&1
	/bin/rm -f $(PI_DIR)/* >/dev/null 2>&1
	/bin/rm -f $(PI_JESSIE_DIR)/* >/dev/null 2>&1
	/bin/rm -f $(MAC_DIR)/* >/dev/null 2>&1
	/bin/rm -f $(NATIVE_DIR)/* >/dev/null 2>&1
